"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FahrenheitToCelsius.py']
DATA_FILES = []
OPTIONS = {"iconfile" : "/Users/ayaanshahab/Documents/GitHub/TemperatureConvert/icons8-temperature-48.icns"}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
